# .github/workflows/check.yml

name: Netravati Slot Checker

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Selenium
        run: pip install selenium

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: latest

      - name: Run slot checker
        env:
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          CHROME_BINARY: /usr/bin/google-chrome
          CHROME_DRIVER: /usr/bin/chromedriver
        run: |
          python netravati_slot_checker.py
